development:
  dialect: postgres
  database: mygowebapp
  user: postgres
  password: newpassword
  host: localhost
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@localhost:5432/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@localhost:5432/myapp_production"}}